version: '3.3'

services:
  intensely-postgres:
    container_name: intensely-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGPASSWORD: admin
    build:
      context: ./services/db
    ports:
      - '5433:5433'
    networks:
      - 'backend-net'

  intensely-api:
    container_name: intensely-api
    build:
      context: ./services/api
    ports:
      - '9001:9001'
    volumes:
      - './services/api:/src/api'
      - '/src/api/node_modules'
    environment:
      NODE_ENV: 'dev'
      port: '9001'
      BABEL_DISABLE_CACHE: 1
      JWT_SECRET: 'H34e626&D7'
      JWT_COOKIE_NAME: 'intensely-token'
      DATABASE_URL: 'postgres://admin:admin@intensely-postgres:5433/intensely'
      DATABASE_TEST_URL: 'postgres://admin:admin@intensely-postgres:5433/intensely-integration'
    networks:
      - 'backend-net'
      - 'frontend-net'

  intensely-web:
    container_name: intensely-web
    build:
      context: ./client
    ports:
      - '3000:3000'
      - '35729:35729'
    environment:
      NODE_ENV: 'development'
      CHOKIDAR_USEPOLLING: 1
      JWT_SECRET: 'H34e626&D7'
      JWT_COOKIE_NAME: 'intensely-token'
    volumes:
      - './client:/src/app'
      - '/src/app/node_modules'
    depends_on:
      - 'intensely-postgres'
      - 'intensely-api'
    networks:
      - 'frontend-net'

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
