import typesCreator from '../../setup/types-creator'

export default typesCreator('games',
  'FETCH_REQUEST',
  'FETCH_SUCCESS', 
  'ADD_TO_QUEUE_REQUEST',
  'ADD_TO_QUEUE_SUCCESS', 
  'INVITE_REQUEST', 
  'INVITE_SUCCESS', 
  'ACCEPT_INVITE_TO_PLAY_REQUEST',
  'ACCEPT_INVITE_TO_PLAY_SUCCESS',
  'FETCH_TIC_TAC_TOE_GAME_REQUEST',
  'FETCH_TIC_TAC_TOE_GAME_SUCCESS'
)
